"""Static V8.5 mythopoetic narrative catalog rows."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass


@dataclass(frozen=True)
class NarrativePatternRow:
    label: str
    family: str
    taxonomy_path: tuple[str, ...]
    narrative_intent: str
    archetypal_structure: tuple[str, ...]
    journey_arc: tuple[str, ...]
    ritual_structure: tuple[str, ...]
    emotional_arc: tuple[str, ...]
    symbolic_transitions: tuple[str, ...]
    visual_mappings: tuple[str, ...]
    motion_mappings: tuple[str, ...]
    audio_mappings: tuple[str, ...]
    spatial_installation_mappings: tuple[str, ...]
    creative_brief_points: tuple[str, ...]
    explanation_points: tuple[str, ...]
    audience_communication: tuple[str, ...]
    boundary: str


UNSUPPORTED_NARRATIVE_CLAIM_TOKENS = frozenset(
    {
        "clinical",
        "cure",
        "diagnose",
        "diagnosis",
        "divine",
        "doctrine",
        "efficacy",
        "enlightenment",
        "guarantee",
        "heal",
        "healing",
        "hidden",
        "initiatory",
        "official",
        "prophecy",
        "prove",
        "psychological",
        "psychotherapy",
        "religious",
        "sacred",
        "spiritual",
        "therapeutic",
        "therapy",
        "truth",
        "universal",
    }
)


NARRATIVE_ALIASES: Mapping[str, tuple[str, ...]] = {
    "alchemy": ("death_rebirth_cycle", "threshold_initiation_arc"),
    "archetype": ("archetypal_transformation",),
    "archetypal": ("archetypal_transformation",),
    "ascent": ("heroic_cycle", "threshold_initiation_arc"),
    "audience": ("installation_audience_journey",),
    "awakening": ("threshold_initiation_arc",),
    "brief": ("demo_project_story",),
    "ceremony": ("ritual_procession",),
    "climax": ("heroic_cycle", "death_rebirth_cycle"),
    "concept": ("demo_project_story",),
    "contemplative": ("contemplative_void",),
    "cycle": ("heroic_cycle", "death_rebirth_cycle"),
    "demo": ("demo_project_story",),
    "descent": ("descent_return",),
    "dialogue": ("symbolic_dialogue",),
    "emergence": ("seed_emergence",),
    "exhibition": ("installation_audience_journey",),
    "gallery": ("installation_audience_journey",),
    "gate": ("threshold_initiation_arc", "ritual_procession"),
    "hero": ("heroic_cycle",),
    "heroic": ("heroic_cycle",),
    "initiation": ("threshold_initiation_arc",),
    "installation": ("installation_audience_journey",),
    "journey": ("heroic_cycle", "threshold_initiation_arc"),
    "labyrinth": ("labyrinth_journey", "threshold_initiation_arc"),
    "meditative": ("contemplative_void",),
    "mirror": ("mirror_revelation",),
    "myth": ("archetypal_transformation", "heroic_cycle"),
    "mythic": ("archetypal_transformation", "heroic_cycle"),
    "mythopoetic": ("archetypal_transformation",),
    "ordeal": ("heroic_cycle", "descent_return"),
    "phoenix": ("death_rebirth_cycle",),
    "presentation": ("demo_project_story",),
    "procession": ("ritual_procession", "installation_audience_journey"),
    "rebirth": ("death_rebirth_cycle",),
    "reflection": ("mirror_revelation", "contemplative_void"),
    "ritual": ("ritual_procession",),
    "scene": ("demo_project_story",),
    "seed": ("seed_emergence",),
    "showcase": ("demo_project_story",),
    "silence": ("contemplative_void",),
    "spatial": ("installation_audience_journey",),
    "story": ("demo_project_story",),
    "storytelling": ("demo_project_story",),
    "threshold": ("threshold_initiation_arc",),
    "transformation": ("archetypal_transformation", "death_rebirth_cycle"),
    "underworld": ("descent_return",),
    "voice": ("symbolic_dialogue",),
    "void": ("contemplative_void", "descent_return"),
}


SYMBOL_TO_NARRATIVE: Mapping[str, tuple[str, ...]] = {
    "ascent": ("heroic_cycle",),
    "breath": ("ritual_procession", "contemplative_void"),
    "center": ("installation_audience_journey", "contemplative_void"),
    "cycle": ("heroic_cycle", "death_rebirth_cycle"),
    "flame": ("death_rebirth_cycle",),
    "fragmentation": ("death_rebirth_cycle", "descent_return"),
    "gate": ("threshold_initiation_arc",),
    "labyrinth": ("labyrinth_journey",),
    "mandala": ("installation_audience_journey", "contemplative_void"),
    "mirror": ("mirror_revelation",),
    "phoenix": ("death_rebirth_cycle",),
    "pulse": ("ritual_procession",),
    "reintegration": ("death_rebirth_cycle",),
    "seed": ("seed_emergence",),
    "spiral": ("threshold_initiation_arc", "archetypal_transformation"),
    "threshold": ("threshold_initiation_arc",),
    "transformation": ("archetypal_transformation",),
    "void": ("contemplative_void", "descent_return"),
}


GEOMETRY_TO_NARRATIVE: Mapping[str, tuple[str, ...]] = {
    "biological_growth": ("seed_emergence",),
    "cellular_automata": ("seed_emergence", "demo_project_story"),
    "flow_field": ("installation_audience_journey", "ritual_procession"),
    "fractal_structure": ("archetypal_transformation",),
    "golden_ratio": ("demo_project_story", "installation_audience_journey"),
    "harmonic_proportion": ("ritual_procession",),
    "l_system_growth": ("seed_emergence",),
    "mandala_generator": ("installation_audience_journey", "contemplative_void"),
    "particle_geometry": ("death_rebirth_cycle", "installation_audience_journey"),
    "reaction_diffusion": ("death_rebirth_cycle", "seed_emergence"),
    "recursive_spiral": ("threshold_initiation_arc", "archetypal_transformation"),
    "sacred_polygon_circle_grid": ("installation_audience_journey",),
    "sacred_tessellation": ("ritual_procession", "installation_audience_journey"),
    "temple_axis": ("ritual_procession", "threshold_initiation_arc"),
}


ARCHITECTURE_TO_NARRATIVE: Mapping[str, tuple[str, ...]] = {
    "axis_threshold_procession": ("threshold_initiation_arc", "ritual_procession"),
    "central_periphery_mandala_plan": ("installation_audience_journey", "contemplative_void"),
    "compressed_threshold_chamber_sequence": ("threshold_initiation_arc", "descent_return"),
    "courtyard_cloister_perimeter": ("contemplative_void", "installation_audience_journey"),
    "gothic_vertical_light_axis": ("heroic_cycle", "threshold_initiation_arc"),
    "installation_gallery_sequence": ("installation_audience_journey", "demo_project_story"),
    "labyrinthine_procession_path": ("labyrinth_journey", "ritual_procession"),
    "modular_hypostyle_grid": ("ritual_procession", "demo_project_story"),
    "pavilion_field_environment": ("installation_audience_journey", "seed_emergence"),
    "tessellated_courtyard_field": ("ritual_procession", "installation_audience_journey"),
}


PATTERN_ROWS: Mapping[str, NarrativePatternRow] = {
    "archetypal_transformation": NarrativePatternRow(
        label="Archetypal Transformation",
        family="transformation",
        taxonomy_path=("mythopoetic narrative", "archetype", "transformation"),
        narrative_intent="Frame a visible change from known state to disrupted threshold to integrated form.",
        archetypal_structure=("Known world", "disruption", "threshold", "ordeal", "integration"),
        journey_arc=(
            "Establish ordinary pattern.",
            "Introduce symbolic pressure.",
            "Cross into change.",
            "Resolve visibly.",
        ),
        ritual_structure=("Opening mark", "focused action", "threshold shift", "return signal"),
        emotional_arc=("orientation", "tension", "uncertainty", "release", "clarity"),
        symbolic_transitions=("pattern -> rupture", "rupture -> threshold", "threshold -> integration"),
        visual_mappings=("Show before/after states through form, density, palette, or topology.",),
        motion_mappings=("Use staged interpolation so the transformation can be read over time.",),
        audio_mappings=("Shift texture, register, or density across the same phases when audio is requested.",),
        spatial_installation_mappings=("Let the viewer encounter one clear threshold between old and new states.",),
        creative_brief_points=("Make transformation observable, staged, and inspectable.",),
        explanation_points=("The arc is a creative structure for change, not a universal myth claim.",),
        audience_communication=("Describe what changes, what remains continuous, and why the transition matters.",),
        boundary="Archetypes are used as creative composition scaffolds, not psychological or spiritual authority.",
    ),
    "death_rebirth_cycle": NarrativePatternRow(
        label="Death and Rebirth Cycle",
        family="transformation",
        taxonomy_path=("mythopoetic narrative", "cycle", "death rebirth"),
        narrative_intent="Use dissolution, residue, recomposition, and return as a bounded creative arc.",
        archetypal_structure=("coherent form", "dissolution", "ember or residue", "reassembly", "renewed form"),
        journey_arc=(
            "Show what is lost.",
            "Break the form apart.",
            "Hold a quiet residue.",
            "Rebuild with difference.",
        ),
        ritual_structure=("release", "pause", "gather", "return"),
        emotional_arc=("recognition", "loss", "suspense", "hope", "renewal"),
        symbolic_transitions=("coherence -> fragments", "fragments -> seed", "seed -> renewed coherence"),
        visual_mappings=("Use particles, sparks, shards, or opacity loss followed by visible reassembly.",),
        motion_mappings=("Move from collapse or dispersal into rising or convergent motion.",),
        audio_mappings=("Use muted texture into brighter layers only when audio is part of the request.",),
        spatial_installation_mappings=("Place the quietest point near a threshold, center, or audience pause node.",),
        creative_brief_points=("Build a clear phoenix-style before, dissolution, and reformed state.",),
        explanation_points=("Rebirth is a creative metaphor for visual recomposition.",),
        audience_communication=("Emphasize the changed return rather than claiming renewal as an external truth.",),
        boundary="Death/rebirth language remains metaphorical creative framing, not religious or therapeutic guidance.",
    ),
    "threshold_initiation_arc": NarrativePatternRow(
        label="Threshold and Initiation Arc",
        family="initiation",
        taxonomy_path=("mythopoetic narrative", "journey", "threshold"),
        narrative_intent="Structure the experience as approach, crossing, altered state, and careful return.",
        archetypal_structure=("approach", "gate", "crossing", "encounter", "return with mark"),
        journey_arc=("Invite approach.", "Make the boundary visible.", "Cross deliberately.", "Return with a cue."),
        ritual_structure=("preparation", "threshold mark", "passage", "closing gesture"),
        emotional_arc=("curiosity", "attention", "uncertainty", "intensity", "grounding"),
        symbolic_transitions=("outside -> gate", "gate -> passage", "passage -> return"),
        visual_mappings=("Use apertures, gates, split fields, or boundary lines to mark crossing.",),
        motion_mappings=("Tie camera, particles, or state changes to crossing progress.",),
        audio_mappings=("Mark the threshold with restrained rhythm or filter change when audio is requested.",),
        spatial_installation_mappings=("Stage entry, crossing, center, and exit as distinct audience positions.",),
        creative_brief_points=("Make the threshold legible and the return bounded.",),
        explanation_points=("Initiation is treated as a narrative structure, not an initiatory claim.",),
        audience_communication=("Name the passage clearly as an experiential transition designed by the artist.",),
        boundary="Threshold guidance does not validate initiation, lineage, ritual rank, or spiritual authority.",
    ),
    "heroic_cycle": NarrativePatternRow(
        label="Heroic Cycle",
        family="heroic_cycle",
        taxonomy_path=("mythopoetic narrative", "journey", "heroic cycle"),
        narrative_intent="Adapt call, challenge, ordeal, insight, and return into project storytelling.",
        archetypal_structure=("call", "departure", "ordeal", "insight", "return"),
        journey_arc=(
            "Open with a clear need.",
            "Show the challenge.",
            "Make the ordeal visible.",
            "Return with value.",
        ),
        ritual_structure=("call signal", "trial", "recognition", "return signal"),
        emotional_arc=("invitation", "risk", "pressure", "recognition", "confidence"),
        symbolic_transitions=("call -> departure", "departure -> ordeal", "ordeal -> insight", "insight -> return"),
        visual_mappings=("Move from sparse statement to full system demonstration and resolved composition.",),
        motion_mappings=("Increase movement complexity through the ordeal, then simplify for the return.",),
        audio_mappings=("Use gradual build, peak, and settled cadence only when audio is requested.",),
        spatial_installation_mappings=("Lead viewers from introduction to challenge zone to resolved vantage point.",),
        creative_brief_points=("Use a clear problem, transformation, and value return for demo storytelling.",),
        explanation_points=("The heroic cycle is a presentation rhythm, not a claim about the audience.",),
        audience_communication=("Explain what the work attempts, what it overcomes, and what it leaves viewers with.",),
        boundary="Heroic structure remains project framing and does not assign psychological roles to viewers.",
    ),
    "descent_return": NarrativePatternRow(
        label="Descent and Return",
        family="descent_return",
        taxonomy_path=("mythopoetic narrative", "journey", "descent return"),
        narrative_intent="Guide a movement into obscurity, compression, or difficulty before re-emergence.",
        archetypal_structure=("surface", "descent", "depth", "finding", "return"),
        journey_arc=("Begin legibly.", "Compress or darken.", "Hold the depth.", "Recover a transformed signal."),
        ritual_structure=("entry", "descent mark", "holding pattern", "return"),
        emotional_arc=("orientation", "gravity", "uncertainty", "recognition", "relief"),
        symbolic_transitions=("surface -> depth", "depth -> finding", "finding -> return"),
        visual_mappings=("Use dark fields, occlusion, compression, or reduced detail before reveal.",),
        motion_mappings=("Move downward, inward, or slower before releasing outward or upward.",),
        audio_mappings=("Use low texture or reduced bandwidth before opening the sound field if requested.",),
        spatial_installation_mappings=(
            "Create a compressed chamber, pause zone, or inward path before opening space.",
        ),
        creative_brief_points=("Keep the descent readable and the return materially different.",),
        explanation_points=("Depth is a compositional state, not an underworld doctrine.",),
        audience_communication=("Describe descent as a designed contrast that makes return perceptible.",),
        boundary="Descent language is metaphorical and does not claim esoteric geography or therapy.",
    ),
    "seed_emergence": NarrativePatternRow(
        label="Seed Emergence",
        family="emergence",
        taxonomy_path=("mythopoetic narrative", "growth", "seed emergence"),
        narrative_intent="Begin with a compact origin that unfolds into structure, complexity, or environment.",
        archetypal_structure=("seed", "first motion", "branching", "field", "mature pattern"),
        journey_arc=("Show origin.", "Let rules activate.", "Branch or unfold.", "Reveal the full field."),
        ritual_structure=("planting", "germination", "growth rhythm", "rest"),
        emotional_arc=("quiet", "curiosity", "momentum", "abundance", "settled attention"),
        symbolic_transitions=("seed -> rule", "rule -> growth", "growth -> field"),
        visual_mappings=("Use growth, branching, recursion, or reaction-diffusion as visible emergence.",),
        motion_mappings=("Animate growth rate, branching depth, or field expansion with bounded parameters.",),
        audio_mappings=("Layer sparse motifs into denser rhythms only when audio is requested.",),
        spatial_installation_mappings=("Let the audience discover the origin before seeing the full environment.",),
        creative_brief_points=("Keep origin, rule, and expanded result connected.",),
        explanation_points=("Emergence is a generative process description, not a life claim.",),
        audience_communication=("Explain the seed rule and how it expands into the final composition.",),
        boundary="Seed emergence is procedural framing and does not claim biological or creation authority.",
    ),
    "ritual_procession": NarrativePatternRow(
        label="Ritual Procession",
        family="procession",
        taxonomy_path=("mythopoetic narrative", "ritual", "procession"),
        narrative_intent="Use repeated actions, thresholds, and pacing to structure an experiential sequence.",
        archetypal_structure=("gather", "repeat", "cross", "focus", "release"),
        journey_arc=("Begin with a repeated cue.", "Advance through thresholds.", "Focus attention.", "Close gently."),
        ritual_structure=("opening cadence", "processional rhythm", "threshold marker", "closing return"),
        emotional_arc=("arrival", "attunement", "anticipation", "focus", "release"),
        symbolic_transitions=("arrival -> cadence", "cadence -> threshold", "threshold -> focus"),
        visual_mappings=("Use repeated marks, light shifts, or pattern density as processional cues.",),
        motion_mappings=("Use stepwise reveals, pulses, or path-following instead of abrupt scene cuts.",),
        audio_mappings=("Use pulse, drone, or call-response only as aesthetic pacing when audio is requested.",),
        spatial_installation_mappings=("Map repeated cues to entry, path, pause, focus, and exit zones.",),
        creative_brief_points=("Make repeated actions intentional and bounded.",),
        explanation_points=("Ritual structure is process design, not ritual efficacy.",),
        audience_communication=("Describe the procession as a designed sequence of attention and pacing.",),
        boundary="Ritual language is treated as processional structure without religious authority or efficacy claims.",
    ),
    "labyrinth_journey": NarrativePatternRow(
        label="Labyrinth Journey",
        family="initiation",
        taxonomy_path=("mythopoetic narrative", "journey", "labyrinth"),
        narrative_intent="Use path, delay, encounter, and return to make navigation narratively meaningful.",
        archetypal_structure=("entry", "turning", "center", "reorientation", "exit"),
        journey_arc=("Enter the path.", "Lose directness.", "Find a center.", "Return with changed orientation."),
        ritual_structure=("entry mark", "turning rhythm", "center pause", "exit"),
        emotional_arc=("curiosity", "disorientation", "attention", "recognition", "orientation"),
        symbolic_transitions=("path -> delay", "delay -> center", "center -> exit"),
        visual_mappings=("Draw winding routes, nested paths, or navigable line fields with a readable path.",),
        motion_mappings=("Move a highlight, camera, or particle through the route with deliberate pacing.",),
        audio_mappings=("Use echo, delay, or call-response as optional navigation support.",),
        spatial_installation_mappings=("Design path, center, dwell point, and exit as distinct spatial beats.",),
        creative_brief_points=("Keep the path legible enough for audience interpretation.",),
        explanation_points=("Labyrinth is navigation and delay, not an esoteric map.",),
        audience_communication=("Invite viewers to notice how indirect movement changes perception.",),
        boundary="Labyrinth guidance remains experiential navigation and avoids hidden-map claims.",
    ),
    "mirror_revelation": NarrativePatternRow(
        label="Mirror Revelation",
        family="reflection",
        taxonomy_path=("mythopoetic narrative", "reflection", "mirror"),
        narrative_intent="Use reflection, doubling, divergence, and recognition as a narrative sequence.",
        archetypal_structure=("image", "double", "distortion", "recognition", "choice"),
        journey_arc=("Establish reflection.", "Introduce difference.", "Reveal a pattern.", "Resolve deliberately."),
        ritual_structure=("facing", "doubling", "recognition", "release"),
        emotional_arc=("attention", "unease", "curiosity", "recognition", "agency"),
        symbolic_transitions=("image -> double", "double -> distortion", "distortion -> recognition"),
        visual_mappings=("Use symmetry, reflected layers, or paired forms that diverge and realign.",),
        motion_mappings=("Let mirrored elements phase apart before returning or choosing different paths.",),
        audio_mappings=("Use stereo, echo, or call-response only when audio is requested.",),
        spatial_installation_mappings=("Use facing zones, reflective surfaces, or paired sightlines as spatial cues.",),
        creative_brief_points=("Make divergence intentional so reflection has narrative weight.",),
        explanation_points=("Reflection is formal and experiential, not psychological assessment.",),
        audience_communication=("Describe the mirror as a device for noticing relation and difference.",),
        boundary="Mirror guidance does not diagnose audience identity, emotion, or psychology.",
    ),
    "contemplative_void": NarrativePatternRow(
        label="Contemplative Void",
        family="contemplation",
        taxonomy_path=("mythopoetic narrative", "contemplation", "void"),
        narrative_intent="Use quiet, negative space, reduced motion, and return of attention as structure.",
        archetypal_structure=("noise", "reduction", "void", "subtle signal", "return"),
        journey_arc=("Reduce density.", "Hold empty space.", "Let a subtle cue appear.", "Return slowly."),
        ritual_structure=("quieting", "pause", "small signal", "closing"),
        emotional_arc=("settling", "suspense", "stillness", "attention", "soft release"),
        symbolic_transitions=("density -> absence", "absence -> signal", "signal -> return"),
        visual_mappings=("Protect negative space and use sparse marks, dark fields, or quiet luminance.",),
        motion_mappings=("Slow motion sharply and make micro-change perceptible.",),
        audio_mappings=("Use silence, low texture, or sparse tones only when audio is requested.",),
        spatial_installation_mappings=("Create a dwell area with low stimulus and a clear exit back to activity.",),
        creative_brief_points=("Let absence be a designed event, not an unfinished state.",),
        explanation_points=("Void is a perceptual device and does not assert metaphysical truth.",),
        audience_communication=("Invite attention to pacing, absence, and subtle change.",),
        boundary="Contemplative guidance is experiential pacing, not spiritual instruction or therapy.",
    ),
    "installation_audience_journey": NarrativePatternRow(
        label="Installation Audience Journey",
        family="installation",
        taxonomy_path=("mythopoetic narrative", "installation", "audience journey"),
        narrative_intent="Translate story into entry, path, dwell, reveal, and exit for spatial experiences.",
        archetypal_structure=("entry", "orientation", "threshold", "dwell", "exit"),
        journey_arc=("Orient viewers.", "Guide movement.", "Offer a focal event.", "Leave a closing trace."),
        ritual_structure=("arrival cue", "processional path", "dwell moment", "exit cue"),
        emotional_arc=("arrival", "curiosity", "attention", "immersion", "afterimage"),
        symbolic_transitions=("entry -> path", "path -> dwell", "dwell -> exit"),
        visual_mappings=("Bind visual intensity to viewer path, focal zones, or dwell points.",),
        motion_mappings=("Use movement to direct attention rather than simulate audience behavior.",),
        audio_mappings=("Map optional sound zones to entry, dwell, and exit without autoplay assumptions.",),
        spatial_installation_mappings=("Define entry, threshold, center, side zones, sightlines, and exit.",),
        creative_brief_points=("State how viewers move through the work and what each zone contributes.",),
        explanation_points=("Audience journey is spatial dramaturgy, not audience transformation measurement.",),
        audience_communication=("Explain the intended route, focal moments, and safe interaction expectations.",),
        boundary="Audience guidance is design intent and does not claim measurable psychological transformation.",
    ),
    "demo_project_story": NarrativePatternRow(
        label="Demo Project Story",
        family="demo_story",
        taxonomy_path=("mythopoetic narrative", "project framing", "demo story"),
        narrative_intent="Convert concept, technical method, and experience into a clear demo-ready story.",
        archetypal_structure=("problem", "concept", "method", "experience", "value"),
        journey_arc=("Name the intent.", "Show the generative method.", "Explain the experience.", "Close value."),
        ritual_structure=("opening statement", "method reveal", "result explanation", "closing claim boundary"),
        emotional_arc=("clarity", "curiosity", "understanding", "appreciation", "readiness"),
        symbolic_transitions=("intent -> method", "method -> experience", "experience -> value"),
        visual_mappings=("Choose a few readable visual hooks that can be explained quickly.",),
        motion_mappings=("Describe motion as part of the concept rather than just effect polish.",),
        audio_mappings=("Explain audio only when it is part of the actual concept or requested runtime.",),
        spatial_installation_mappings=(
            "Tie spatial claims to available concept guidance, not future preview systems.",
        ),
        creative_brief_points=("Summarize audience, intent, medium, narrative arc, and constraints.",),
        explanation_points=("Separate what is implemented from what is conceptual or future-facing.",),
        audience_communication=("Use precise demo language that avoids product, spiritual, or OS overclaims.",),
        boundary="Demo story building frames current capability only and does not start V8.8 showcase systems.",
    ),
    "symbolic_dialogue": NarrativePatternRow(
        label="Symbolic Dialogue",
        family="dialogue",
        taxonomy_path=("mythopoetic narrative", "dialogue", "symbolic voices"),
        narrative_intent="Represent tensions between symbols, states, or forces as bounded dialogue cues.",
        archetypal_structure=("voice A", "voice B", "tension", "exchange", "temporary alignment"),
        journey_arc=("Name the voices.", "Stage contrast.", "Let exchange alter the field.", "Close with relation."),
        ritual_structure=("call", "response", "counter-response", "settled relation"),
        emotional_arc=("attention", "tension", "listening", "recognition", "balance"),
        symbolic_transitions=("voice -> response", "response -> tension", "tension -> relation"),
        visual_mappings=("Use paired forms, colors, or fields that answer each other visibly.",),
        motion_mappings=("Use call-response timing, alternation, or phase offsets.",),
        audio_mappings=("Use call-response or stereo contrast only when audio is requested.",),
        spatial_installation_mappings=("Place voices as opposing zones, paired objects, or alternating sightlines.",),
        creative_brief_points=("Define what each voice represents in user-authored creative terms.",),
        explanation_points=("Dialogue cues are compositional tensions, not channeled or authoritative voices.",),
        audience_communication=("Explain the dialogue as a relation between visible design states.",),
        boundary="Symbolic dialogue does not claim external voice, oracle, channeling, or esoteric authority.",
    ),
}


ROADMAP_CLASSIFICATION_ROWS: Mapping[str, tuple[str, str, bool, bool]] = {
    "Narrative Symbol Graph": (
        "implemented_runtime_behavior",
        "Implemented as bounded symbol nodes and edges derived from selected narrative patterns.",
        False,
        False,
    ),
    "Initiatory Journey Generator": (
        "implemented_runtime_behavior",
        "Implemented as threshold/initiation journey guidance while blocking initiatory authority claims.",
        False,
        False,
    ),
    "Archetypal Transformation Engine": (
        "implemented_runtime_behavior",
        "Implemented through archetypal transformation and transformation-cycle pattern contracts.",
        False,
        False,
    ),
    "Heroic Cycle Engine": (
        "implemented_runtime_behavior",
        "Implemented as demo/project storytelling rhythm with call, challenge, insight, and return.",
        False,
        False,
    ),
    "Multi-layer Narrative Generator": (
        "implemented_runtime_behavior",
        "Implemented across narrative, emotional, visual, motion, audio, and spatial layers.",
        False,
        False,
    ),
    "Mythic Scene Composer": (
        "implemented_runtime_behavior",
        "Implemented as deterministic scene-sequence beats with narrative functions and mappings.",
        False,
        False,
    ),
    "Symbolic Dialogue Engine": (
        "implemented_runtime_behavior",
        "Implemented as bounded dialogue cues between user-visible symbols or design states.",
        False,
        False,
    ),
    "Temporal Narrative Engine": (
        "implemented_runtime_behavior",
        "Implemented through ordered scene phases, transitions, and temporal pacing guidance.",
        False,
        False,
    ),
    "Spatial Narrative Engine": (
        "implemented_runtime_behavior",
        "Implemented through spatial and installation mappings, reusing V8.4 where available.",
        False,
        False,
    ),
    "Mystical Journey Planner": (
        "partial_reusable",
        "Supported only as bounded contemplative or mythopoetic journey language; mystical authority is blocked.",
        False,
        False,
    ),
    "Ritual Structure Engine": (
        "implemented_runtime_behavior",
        "Implemented as processional pacing, repeated cues, thresholds, and closure without ritual efficacy claims.",
        False,
        False,
    ),
    "Emotional Arc Generator": (
        "implemented_runtime_behavior",
        "Implemented as inspectable emotional progressions for scenes and patterns.",
        False,
        False,
    ),
    "Symbolic Transition Engine": (
        "implemented_runtime_behavior",
        "Implemented through pattern transitions and scene transition_out fields.",
        False,
        False,
    ),
    "Narrative Explainability": (
        "implemented_runtime_behavior",
        "Implemented through concept explanation, evidence, provenance, boundaries, and prompt lines.",
        False,
        False,
    ),
    "Narrative Provenance": (
        "implemented_runtime_behavior",
        "Implemented with V8.1, V8.2, V8.3, V8.4, catalog, and request provenance records.",
        False,
        False,
    ),
    "Narrative Validation": (
        "implemented_runtime_behavior",
        "Implemented as deterministic validation findings for scope, safety, and later-capability boundaries.",
        False,
        False,
    ),
    "Esoteric Narrative Grammar": (
        "partial_reusable",
        "Implemented only as bounded creative grammar; esoteric authority and doctrine are unsupported.",
        False,
        False,
    ),
    "Contemplative Experience Planner": (
        "implemented_runtime_behavior",
        "Implemented as contemplative pacing and void/quiet guidance without spiritual instruction.",
        False,
        False,
    ),
    "Audience Transformation Model": (
        "implemented_runtime_behavior",
        "Implemented as intended audience experience and communication, not psychological measurement.",
        False,
        False,
    ),
    "Creative Project Storytelling": (
        "implemented_runtime_behavior",
        "Implemented through project-story and demo-story narrative fields.",
        False,
        False,
    ),
    "Installation Narrative": (
        "implemented_runtime_behavior",
        "Implemented through installation audience journey and V8.4 spatial reuse.",
        False,
        False,
    ),
    "Creative Brief Generator": (
        "implemented_runtime_behavior",
        "Implemented as compact creative_brief output assembled from selected patterns.",
        False,
        False,
    ),
    "Concept Development": (
        "implemented_runtime_behavior",
        "Implemented through concept explanation and creative-brief expansion points.",
        False,
        False,
    ),
    "Presentation Narrative": (
        "implemented_runtime_behavior",
        "Implemented as presentation_narrative guidance for explaining the concept.",
        False,
        False,
    ),
    "Demo Story Builder": (
        "implemented_runtime_behavior",
        "Implemented as demo_story guidance without starting V8.8 showcase systems.",
        False,
        False,
    ),
    "Audience Communication": (
        "implemented_runtime_behavior",
        "Implemented as audience-facing wording guidance and boundary-aware communication.",
        False,
        False,
    ),
}


__all__ = [
    "ARCHITECTURE_TO_NARRATIVE",
    "GEOMETRY_TO_NARRATIVE",
    "NARRATIVE_ALIASES",
    "PATTERN_ROWS",
    "ROADMAP_CLASSIFICATION_ROWS",
    "SYMBOL_TO_NARRATIVE",
    "UNSUPPORTED_NARRATIVE_CLAIM_TOKENS",
    "NarrativePatternRow",
]
