"""Static V8.3 sacred geometry catalog rows."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass


@dataclass(frozen=True)
class GeometryBlueprintRow:
    label: str
    family: str
    taxonomy_path: tuple[str, ...]
    creative_intent: str
    structure: tuple[str, ...]
    algorithms: tuple[str, ...]
    parameters: tuple[str, ...]
    motion: tuple[str, ...]
    color_light: tuple[str, ...]
    audio: tuple[str, ...]
    runtimes: tuple[str, ...]
    notes: tuple[str, ...]
    boundary: str


DOMAIN_RUNTIME_NAMES: Mapping[str, str] = {
    "canvas_2d": "Canvas 2D",
    "glsl": "GLSL",
    "p5_js": "p5.js",
    "p5_sound": "p5.js",
    "react_three_fiber": "React Three Fiber",
    "three_js": "Three.js",
    "tone_js": "Tone.js",
    "web_audio_api": "Web Audio API",
    "webgpu_wgsl": "WebGPU/WGSL",
}


UNSUPPORTED_CLAIM_TOKENS = frozenset(
    {
        "absolute",
        "ancient",
        "cosmic",
        "divine",
        "esoteric",
        "metaphysical",
        "mystical",
        "prove",
        "proof",
        "truth",
        "universal",
    }
)


GEOMETRY_ALIASES: Mapping[str, tuple[str, ...]] = {
    "automata": ("cellular_automata",),
    "branch": ("l_system_growth",),
    "branching": ("l_system_growth",),
    "cellular": ("cellular_automata",),
    "circle": ("sacred_polygon_circle_grid",),
    "diffusion": ("reaction_diffusion",),
    "egyptian": ("egyptian_grid",),
    "fibonacci": ("golden_ratio", "recursive_spiral"),
    "field": ("flow_field",),
    "fields": ("flow_field",),
    "flow": ("flow_field",),
    "fractal": ("fractal_structure",),
    "frattle": ("fractal_structure",),
    "geometry": ("sacred_polygon_circle_grid",),
    "gothic": ("gothic_geometry",),
    "grid": ("sacred_polygon_circle_grid",),
    "growth": ("l_system_growth", "biological_growth"),
    "harmonic": ("harmonic_proportion",),
    "islamic": ("islamic_tessellation",),
    "lattice": ("sacred_tessellation",),
    "lsystem": ("l_system_growth",),
    "mandala": ("mandala_generator",),
    "morphogenesis": ("reaction_diffusion", "biological_growth"),
    "particle": ("particle_geometry",),
    "particles": ("particle_geometry",),
    "phi": ("golden_ratio",),
    "platonic": ("platonic_solid",),
    "polygon": ("sacred_polygon_circle_grid",),
    "proportion": ("harmonic_proportion", "golden_ratio"),
    "reaction": ("reaction_diffusion",),
    "recursive": ("recursive_spiral",),
    "recursion": ("recursive_spiral",),
    "ratio": ("golden_ratio", "harmonic_proportion"),
    "sacred": ("sacred_polygon_circle_grid",),
    "solid": ("platonic_solid",),
    "solids": ("platonic_solid",),
    "spiral": ("recursive_spiral", "golden_ratio"),
    "temple": ("temple_axis",),
    "tessellation": ("sacred_tessellation", "islamic_tessellation"),
    "tiling": ("sacred_tessellation",),
    "yantra": ("yantra_generator",),
}

BLUEPRINT_ROWS: Mapping[str, GeometryBlueprintRow] = {
    "golden_ratio": GeometryBlueprintRow(
        label="Golden Ratio Proportion",
        family="proportion",
        taxonomy_path=("creative geometry", "proportion", "golden ratio"),
        creative_intent="Use phi-based proportions as a visible compositional and growth scaffold.",
        structure=("Divide canvas, radii, or nested rectangles by phi relationships.",),
        algorithms=("Golden rectangle subdivision", "Fibonacci or logarithmic spiral scaffold"),
        parameters=("phi: 1.61803398875", "scale_step: 0.618-1.618", "spiral_turns: 2-9"),
        motion=("Animate radius or scale by phi-related steps instead of uniform increments.",),
        color_light=("Use phi-spaced palette stops or luminance bands for nested structure.",),
        audio=("Map adjacent harmonic layers to simple ratios near 3:2, 5:3, or 8:5 when audio is present.",),
        runtimes=("p5.js", "GLSL", "Three.js"),
        notes=("Keep phi visible as proportion guidance, not as proof of quality.",),
        boundary="Golden ratio guidance is mathematical composition support, not universal beauty proof.",
    ),
    "harmonic_proportion": GeometryBlueprintRow(
        label="Harmonic Proportion",
        family="proportion",
        taxonomy_path=("creative geometry", "proportion", "harmonic ratios"),
        creative_intent="Use small integer ratios to coordinate spacing, timing, frequency, and scale.",
        structure=("Build nested widths, radii, and intervals from 1:1, 2:1, 3:2, 4:3, and 5:4 ratios.",),
        algorithms=("Integer-ratio grid", "Harmonic interval parameter ladder"),
        parameters=("ratio_set: 1/1 2/1 3/2 4/3 5/4", "base_unit: viewport-relative", "layer_count: 3-8"),
        motion=("Bind loop durations or angular speeds to ratio_set values.",),
        color_light=("Map ratio layers to brightness or saturation intervals with bounded contrast.",),
        audio=("Use octave, fifth, fourth, and third relationships as bounded musical mapping hints.",),
        runtimes=("p5.js", "Tone.js", "GLSL"),
        notes=("Expose the chosen ratio set so generated code remains tunable.",),
        boundary="Harmonic ratios are creative parameter choices, not metaphysical correspondences.",
    ),
    "sacred_polygon_circle_grid": GeometryBlueprintRow(
        label="Polygon, Circle, and Grid Structure",
        family="polygonal",
        taxonomy_path=("creative geometry", "base structures", "polygon circle grid"),
        creative_intent="Construct readable geometry from circles, regular polygons, grids, and radial anchors.",
        structure=("Use center, radius, sides, grid resolution, and ring count as first-class controls.",),
        algorithms=("Regular polygon construction", "Circle packing guide", "Modular grid layout"),
        parameters=("sides: 3-12", "ring_count: 1-9", "grid_resolution: 4-48", "radius: 0.05-0.48"),
        motion=("Rotate, pulse, or phase polygons while preserving side count and center clarity.",),
        color_light=("Assign color by ring, side index, or grid cell state.",),
        audio=("Map side count, ring index, or grid row to simple rhythmic subdivisions.",),
        runtimes=("p5.js", "Canvas 2D", "GLSL"),
        notes=("Prefer stable dimensions and bounded loops for predictable generated sketches.",),
        boundary="The structure is geometric and generative; no symbolic authority is implied.",
    ),
    "mandala_generator": GeometryBlueprintRow(
        label="Mandala Generator",
        family="radial",
        taxonomy_path=("creative geometry", "radial systems", "mandala"),
        creative_intent="Generate centered radial hierarchy with rings, repeated sectors, and motif variation.",
        structure=("Combine radial symmetry, nested rings, mirrored sector motifs, and a legible center.",),
        algorithms=("Polar coordinate sector repetition", "Radial motif instancing"),
        parameters=("radial_symmetry: 4-24", "ring_count: 2-10", "motif_density: 0.15-0.85"),
        motion=("Use slow counter-rotation, phase reveal, or ring breathing.",),
        color_light=("Map inner rings to lower luminance and outer rings to accent color or glow.",),
        audio=("Bind rings to rhythm layers or frequency bands only when audio is requested.",),
        runtimes=("p5.js", "GLSL", "Tone.js"),
        notes=("Keep sector count bounded so details remain readable.",),
        boundary="Mandala output is a user-requested radial visual system, not doctrine.",
    ),
    "yantra_generator": GeometryBlueprintRow(
        label="Yantra-Style Geometry Generator",
        family="radial",
        taxonomy_path=("creative geometry", "radial systems", "yantra style"),
        creative_intent="Use nested triangles, square boundaries, circles, and center points as abstract geometry.",
        structure=("Layer triangles, enclosing squares, circles, and a central bindu-like anchor.",),
        algorithms=("Nested polygon composition", "Radial mirror composition"),
        parameters=("triangle_count: 1-9", "enclosure_layers: 1-4", "center_weight: 0.1-0.5"),
        motion=("Reveal layers from center outward or oscillate triangle orientation subtly.",),
        color_light=("Use restrained contrast so linework and center remain inspectable.",),
        audio=("Map layer activation to sparse accents rather than claiming ritual function.",),
        runtimes=("p5.js", "Canvas 2D", "GLSL"),
        notes=("Use style-safe language unless the user supplies explicit cultural context.",),
        boundary="Yantra guidance is bounded visual geometry and does not claim religious authority.",
    ),
    "sacred_tessellation": GeometryBlueprintRow(
        label="Tessellation and Tiling",
        family="tessellation",
        taxonomy_path=("creative geometry", "tiling", "tessellation"),
        creative_intent="Create repeatable tiling systems with local variation and global continuity.",
        structure=("Use tile basis vectors, motif repeats, edge rules, and symmetry groups.",),
        algorithms=("Square, triangular, and hexagonal tiling", "Wallpaper-style motif repetition"),
        parameters=("tile_size: 12-160", "symmetry_order: 2-12", "jitter_amount: 0-0.2"),
        motion=("Ripple phase through neighboring tiles while keeping edge alignment stable.",),
        color_light=("Use tile parity, distance field, or motif index for palette assignment.",),
        audio=("Map tile rows, columns, or groups to sequenced accents if audio is requested.",),
        runtimes=("p5.js", "GLSL", "Canvas 2D"),
        notes=("Validate seams and boundary wrapping when the tile repeats.",),
        boundary="Tessellation is pattern construction, not historical or spiritual attribution.",
    ),
    "islamic_tessellation": GeometryBlueprintRow(
        label="Islamic-Geometry-Inspired Tiling",
        family="cultural_geometry",
        taxonomy_path=("creative geometry", "cultural geometry", "islamic inspired tiling"),
        creative_intent="Use compass-and-straightedge-style star polygons and interlaced tiling carefully.",
        structure=("Build from circles, star polygons, repeated rosettes, and strapwork-like line overlays.",),
        algorithms=("Star polygon rosette", "Radial tile repeat", "Interlaced line overlay"),
        parameters=("star_points: 6-16", "rosette_radius: 0.05-0.35", "line_weight: 0.5-6"),
        motion=("Animate construction lines or tile phase without distorting the underlying repeat.",),
        color_light=("Favor line/fill separation so interlace remains legible.",),
        audio=("Use repetition density as a rhythm density control if audio is part of the request.",),
        runtimes=("p5.js", "Canvas 2D", "GLSL"),
        notes=("Use 'inspired by' wording unless explicit sourced cultural context is provided.",),
        boundary="This is bounded visual tiling guidance, not cultural, religious, or historical authority.",
    ),
    "recursive_spiral": GeometryBlueprintRow(
        label="Recursive Spiral Geometry",
        family="recursive",
        taxonomy_path=("creative geometry", "recursion", "spiral"),
        creative_intent="Generate recursive polar structures whose scale, angle, and depth remain bounded.",
        structure=("Repeat forms along a polar path with decreasing scale and controlled angular step.",),
        algorithms=("Recursive polar subdivision", "Logarithmic spiral instancing"),
        parameters=("recursion_depth: 2-9", "angle_step: 5-137.5", "scale_decay: 0.45-0.9"),
        motion=("Drive phase, radius, or depth reveal with smooth bounded time.",),
        color_light=("Fade saturation or luminance by recursion depth.",),
        audio=("Map recursion depth to layered echo or delay density only when bounded.",),
        runtimes=("p5.js", "GLSL", "Three.js"),
        notes=("Guard recursion depth to avoid runaway render cost.",),
        boundary="Recursive spirals are generative structures, not universal transformation laws.",
    ),
    "fractal_structure": GeometryBlueprintRow(
        label="Fractal Pattern Structure",
        family="fractal",
        taxonomy_path=("creative geometry", "fractal systems", "self similarity"),
        creative_intent="Use self-similar subdivision, escape-time fields, or iterated transforms as structure.",
        structure=("Choose one fractal family and expose iteration count, bailout, and scale controls.",),
        algorithms=("Iterated function system", "Escape-time field", "Recursive subdivision"),
        parameters=("iterations: 4-80", "bailout: 2-16", "scale: 0.2-0.95", "branch_factor: 2-6"),
        motion=("Animate parameters slowly to avoid chaotic unreadability.",),
        color_light=("Color by iteration count, distance estimate, or depth layer.",),
        audio=("Use iteration bands for harmonic or rhythmic layering only when requested.",),
        runtimes=("GLSL", "p5.js", "Three.js"),
        notes=("Prefer deterministic seeds and bounded iteration caps.",),
        boundary="Fractal guidance describes mathematical patterning, not metaphysical recursion.",
    ),
    "l_system_growth": GeometryBlueprintRow(
        label="L-System Growth",
        family="growth",
        taxonomy_path=("creative geometry", "growth systems", "l-system"),
        creative_intent="Model branching growth with explicit grammar, angle, depth, and drawing rules.",
        structure=("Use axiom, production rules, turtle angle, segment length, and depth as the contract.",),
        algorithms=("Deterministic L-system", "Stochastic bounded L-system"),
        parameters=("axiom: F", "turn_angle: 12-45", "depth: 2-7", "length_decay: 0.55-0.9"),
        motion=("Grow branches over time by draw progress or grammar generation.",),
        color_light=("Vary stroke, hue, or brightness by branch depth.",),
        audio=("Map branch generation levels to sparse rhythmic layers if audio is requested.",),
        runtimes=("p5.js", "Canvas 2D", "Three.js"),
        notes=("Validate max segments before generating dense trees.",),
        boundary="Growth grammar is procedural geometry, not a claim of biological life.",
    ),
    "flow_field": GeometryBlueprintRow(
        label="Flow Field",
        family="field",
        taxonomy_path=("creative geometry", "field systems", "flow field"),
        creative_intent="Use vector fields to organize particle movement, line direction, and field texture.",
        structure=("Represent direction as sampled vectors from noise, gradients, attractors, or polar fields.",),
        algorithms=("Perlin/simplex noise vector field", "Attractor field", "Curl-style field approximation"),
        parameters=("field_scale: 0.002-0.08", "flow_strength: 0.1-6", "particle_count: 64-4000"),
        motion=("Advance particles by field direction with damping and respawn rules.",),
        color_light=("Color particles by velocity, angle, or local field strength.",),
        audio=("Use amplitude or frequency bands to modulate flow strength only if audio is requested.",),
        runtimes=("p5.js", "GLSL", "Three.js"),
        notes=("Keep particle counts runtime-appropriate and deterministic when possible.",),
        boundary="Flow fields are motion systems, not unseen energy claims.",
    ),
    "reaction_diffusion": GeometryBlueprintRow(
        label="Reaction Diffusion and Morphogenesis",
        family="morphogenesis",
        taxonomy_path=("creative geometry", "morphogenesis", "reaction diffusion"),
        creative_intent="Guide morphogenetic textures through bounded activator/inhibitor style parameters.",
        structure=("Use feed, kill, diffusion, and time-step controls to create stable organic patterning.",),
        algorithms=("Gray-Scott reaction diffusion guidance", "Morphogenetic texture sampling"),
        parameters=("feed_rate: 0.01-0.09", "kill_rate: 0.03-0.08", "diffusion_a: 0.2-1.2", "steps: 4-80"),
        motion=("Animate simulation steps or parameter interpolation gradually.",),
        color_light=("Map concentration channels to contour lines, lightness, or emission.",),
        audio=("Let low-frequency energy nudge feed or threshold values when audio is requested.",),
        runtimes=("GLSL", "p5.js", "WebGPU/WGSL"),
        notes=("Frame as guidance unless a real simulation implementation is explicitly requested.",),
        boundary="Morphogenesis guidance is visual systems design, not biological proof.",
    ),
    "cellular_automata": GeometryBlueprintRow(
        label="Cellular Automata",
        family="cellular",
        taxonomy_path=("creative geometry", "cellular systems", "automata"),
        creative_intent="Use grid states and local transition rules to create emergent visual order.",
        structure=("Define state count, neighborhood, transition rule, wrap behavior, and update cadence.",),
        algorithms=("Conway-style automata", "Cyclic cellular automata", "Reaction-like grid rule"),
        parameters=("state_count: 2-12", "neighborhood: von_neumann/moore", "update_rate: 1-30"),
        motion=("Step the automaton visibly or interpolate cell state transitions.",),
        color_light=("Map states to discrete palettes with clear contrast.",),
        audio=("Map population counts or state transitions to rhythmic triggers if audio is requested.",),
        runtimes=("p5.js", "Canvas 2D", "GLSL"),
        notes=("Expose seed and rule names for reproducibility.",),
        boundary="Automata show rule-based emergence, not intentional agency.",
    ),
    "particle_geometry": GeometryBlueprintRow(
        label="Particle Geometry System",
        family="particle",
        taxonomy_path=("creative geometry", "particle systems", "geometric particles"),
        creative_intent="Treat particles as geometry carriers constrained by fields, attractors, or shapes.",
        structure=("Bind particle spawn, lifetime, attractors, and constraints to visible geometry.",),
        algorithms=("Shape-constrained particle system", "Attractor/repulsor dynamics", "Particle trails"),
        parameters=("particle_count: 64-6000", "lifetime: 0.5-20", "attractor_strength: -4-4"),
        motion=("Use field-following, orbiting, convergence, or dispersal as geometric behavior.",),
        color_light=("Map lifetime, speed, or target shape distance to glow and opacity.",),
        audio=("Use amplitude to spawn, scatter, or brighten particles only with explicit audio intent.",),
        runtimes=("p5.js", "Three.js", "GLSL"),
        notes=("Keep particles as interpretable geometry, not decorative noise.",),
        boundary="Particle systems are morphogenetic/geometric effects, not physical truth claims.",
    ),
    "platonic_solid": GeometryBlueprintRow(
        label="Platonic Solid Geometry",
        family="three_dimensional",
        taxonomy_path=("creative geometry", "3d forms", "platonic solids"),
        creative_intent="Use regular 3D solids as readable structure, not as metaphysical hierarchy.",
        structure=("Select tetrahedron, cube, octahedron, dodecahedron, or icosahedron with edge/face controls.",),
        algorithms=("Regular polyhedron mesh selection", "Face/edge normal visualization"),
        parameters=("solid_type: tetra/cube/octa/dodeca/icosa", "edge_weight: 0.5-8", "rotation_speed: 0-2"),
        motion=("Rotate slowly, explode faces, or morph between compatible low-poly structures.",),
        color_light=("Light by face normal, edge highlight, or nested shell depth.",),
        audio=("Map solid rotation or face activation to sparse tones only when bounded.",),
        runtimes=("Three.js", "React Three Fiber", "GLSL"),
        notes=("Keep 3D forms inspectable and avoid pretending CAD or DCC integration.",),
        boundary="Platonic solids are geometric meshes here, not ontology.",
    ),
    "temple_axis": GeometryBlueprintRow(
        label="Temple-Axis Composition",
        family="compositional_space",
        taxonomy_path=("creative geometry", "spatial composition", "axis and threshold"),
        creative_intent="Use axis, threshold, nested frames, and procession as abstract spatial composition.",
        structure=("Organize forms along central axes, gateways, courtyards, or nested rectangular fields.",),
        algorithms=("Axial layout scaffold", "Nested threshold composition"),
        parameters=("axis_angle: 0-180", "threshold_count: 1-7", "symmetry_strength: 0-1"),
        motion=("Move camera or particles along the axis with clear threshold crossings.",),
        color_light=("Use light gradients to distinguish entry, center, and boundary zones.",),
        audio=("Use transition accents at thresholds only if audio is requested.",),
        runtimes=("p5.js", "Three.js", "Canvas 2D"),
        notes=("This is layout guidance, not architecture analysis or reverse engineering.",),
        boundary="Temple geometry remains abstract creative composition and does not start V8.4 architecture.",
    ),
    "gothic_geometry": GeometryBlueprintRow(
        label="Gothic-Geometry-Inspired Arcs",
        family="cultural_geometry",
        taxonomy_path=("creative geometry", "cultural geometry", "gothic inspired arcs"),
        creative_intent="Use pointed arches, rose-window radial grids, ribs, and tracery-like subdivision.",
        structure=("Combine arch curves, radial windows, ribs, and repeated lancet proportions.",),
        algorithms=("Pointed arch construction", "Rose-window radial subdivision"),
        parameters=("arch_height: 0.2-0.9", "window_segments: 6-24", "rib_count: 2-16"),
        motion=("Reveal tracery lines or rotate radial windows slowly.",),
        color_light=("Use stained-glass-style cell palettes while keeping geometry primary.",),
        audio=("Use segment activation as gentle accents only when audio is requested.",),
        runtimes=("p5.js", "Canvas 2D", "Three.js"),
        notes=("Avoid historical claims unless supplied by a scoped source.",),
        boundary="Gothic-style guidance is visual geometry, not architectural scholarship.",
    ),
    "egyptian_grid": GeometryBlueprintRow(
        label="Egyptian-Geometry-Inspired Grid",
        family="cultural_geometry",
        taxonomy_path=("creative geometry", "cultural geometry", "egyptian inspired grid"),
        creative_intent="Use strict grids, registers, axial symmetry, and proportion bands as visual structure.",
        structure=("Divide the canvas into registers, axes, repeated glyph-like cells, and bounded silhouettes.",),
        algorithms=("Register grid", "Proportion-band layout", "Axis-aligned motif repeat"),
        parameters=("register_count: 2-9", "grid_columns: 4-24", "symmetry_strength: 0-1"),
        motion=("Animate register reveals or procession along horizontal bands.",),
        color_light=("Use flat color bands and strong silhouette contrast.",),
        audio=("Map registers to layered rhythmic lanes only with explicit audio intent.",),
        runtimes=("p5.js", "Canvas 2D", "GLSL"),
        notes=("Keep cultural references stylistic and user-authored unless sourced.",),
        boundary="Egyptian-inspired grid guidance is bounded visual composition, not Egyptology.",
    ),
    "biological_growth": GeometryBlueprintRow(
        label="Biological Growth Pattern",
        family="growth",
        taxonomy_path=("creative geometry", "growth systems", "biological pattern"),
        creative_intent="Use phyllotaxis, branching, venation, or accretion as bounded growth metaphors.",
        structure=("Define seed points, growth front, branching rule, collision, and density controls.",),
        algorithms=("Phyllotaxis point placement", "Diffusion-limited aggregation guidance", "Branching growth"),
        parameters=("growth_rate: 0.01-1", "branch_probability: 0-0.8", "collision_radius: 1-24"),
        motion=("Show growth front progression and preserve readable lineage.",),
        color_light=("Map age, generation, or density to palette and opacity.",),
        audio=("Use growth stage changes as sparse sonic events only when requested.",),
        runtimes=("p5.js", "Three.js", "GLSL"),
        notes=("State when guidance is biomimetic rather than a scientific simulation.",),
        boundary="Biological growth is a generative visual metaphor unless a validated simulation is requested.",
    ),
}

ROADMAP_CLASSIFICATION_ROWS: Mapping[str, tuple[str, str, bool, bool]] = {
    "Sacred Geometry Engine": (
        "implemented_runtime_behavior",
        "Implemented as deterministic typed pattern, operation, validation, provenance, and confidence contracts.",
        False,
        False,
    ),
    "Golden Ratio Engine": (
        "implemented_runtime_behavior",
        "Golden-ratio pattern guidance exposes phi, scale steps, spiral scaffolds, and safe boundaries.",
        False,
        False,
    ),
    "Platonic Solids Engine": (
        "implemented_runtime_behavior",
        "Regular solid mesh guidance is provided without DCC integration or ontology claims.",
        False,
        False,
    ),
    "Sacred Polygon Engine": (
        "implemented_runtime_behavior",
        "Polygon, circle, grid, ring, and side-count contracts are implemented.",
        False,
        False,
    ),
    "Harmonic Proportion Engine": (
        "implemented_runtime_behavior",
        "Small integer ratio guidance maps proportion across scale, timing, light, and bounded audio.",
        False,
        False,
    ),
    "Recursive Geometry Engine": (
        "implemented_runtime_behavior",
        "Recursive spiral and bounded-depth guidance are implemented with validation constraints.",
        False,
        False,
    ),
    "Temple Geometry Engine": (
        "implemented_runtime_behavior",
        "Implemented as abstract axis, threshold, and spatial-composition guidance, not architecture analysis.",
        False,
        False,
    ),
    "Islamic Geometry Engine": (
        "implemented_runtime_behavior",
        "Implemented as bounded star, rosette, and tiling guidance with cultural-authority caveats.",
        False,
        False,
    ),
    "Gothic Geometry Engine": (
        "implemented_runtime_behavior",
        "Implemented as pointed-arch and rose-window geometry guidance without historical authority claims.",
        False,
        False,
    ),
    "Egyptian Geometry Engine": (
        "implemented_runtime_behavior",
        "Implemented as register-grid and axial-composition guidance without Egyptology claims.",
        False,
        False,
    ),
    "Yantra Generator": (
        "implemented_runtime_behavior",
        "Implemented as abstract nested triangle, square, circle, and center-point geometry guidance.",
        False,
        False,
    ),
    "Mandala Generator": (
        "implemented_runtime_behavior",
        "Implemented as centered radial hierarchy, ring, sector, and motif repetition guidance.",
        False,
        False,
    ),
    "Sacred Tessellation Engine": (
        "implemented_runtime_behavior",
        "Implemented through repeatable tiling contracts, symmetry order, tile size, and seam validation.",
        False,
        False,
    ),
    "L-System Sacred Growth": (
        "implemented_runtime_behavior",
        "Implemented as bounded L-system grammar and turtle-geometry growth guidance.",
        False,
        False,
    ),
    "Fractal Sacred Structures": (
        "implemented_runtime_behavior",
        "Implemented with fractal family, iteration, bailout, scale, and deterministic seed guidance.",
        False,
        False,
    ),
    "Geometry Explainability": (
        "implemented_runtime_behavior",
        "Pattern contracts include taxonomy, intent, algorithms, parameters, evidence, and boundaries.",
        False,
        False,
    ),
    "Geometry Provenance": (
        "implemented_runtime_behavior",
        "Report provenance links request, creative translation, V8.1, V8.2, and bounded catalog sources.",
        False,
        False,
    ),
    "Geometry Evolution": (
        "implemented_runtime_behavior",
        "Implemented as bounded parameter variation, depth reveal, and iterative guidance, not autonomous mutation.",
        False,
        False,
    ),
    "Geometry to Music Mapping": (
        "implemented_runtime_behavior",
        "Implemented as optional ratio, ring, state, and phase to audio/harmonic guidance.",
        False,
        False,
    ),
    "Geometry to Light Mapping": (
        "implemented_runtime_behavior",
        "Implemented as ring, depth, normal, velocity, concentration, and state to light/color guidance.",
        False,
        False,
    ),
    "Geometry to Architecture Mapping": (
        "partial_reusable",
        "Bounded spatial-layout guidance exists; V8.4 architecture/reverse-engineering remains explicitly unstated.",
        True,
        False,
    ),
    "Geometry to Ritual Mapping": (
        "implemented_runtime_behavior",
        "Implemented as user-authored pacing, threshold, and sequence guidance without ritual efficacy claims.",
        False,
        False,
    ),
    "Geometry Validation Engine": (
        "implemented_runtime_behavior",
        "Validation findings flag unsupported claims, heavy algorithms, preview scope, and safe boundaries.",
        False,
        False,
    ),
    "Morphogenesis Geometry": (
        "implemented_runtime_behavior",
        "Reaction diffusion, field, cellular, particle, and growth guidance cover morphogenesis patterns.",
        False,
        False,
    ),
    "Flow Fields": (
        "implemented_runtime_behavior",
        "Vector-field pattern contracts cover particles, lines, force strength, and runtime constraints.",
        False,
        False,
    ),
    "Reaction Diffusion": (
        "implemented_runtime_behavior",
        "Gray-Scott-style feed/kill/diffusion guidance is implemented as bounded visual design guidance.",
        False,
        False,
    ),
    "Cellular Automata": (
        "implemented_runtime_behavior",
        "Grid state, neighborhood, transition, wrap, and update cadence contracts are implemented.",
        False,
        False,
    ),
    "Biological Growth Patterns": (
        "implemented_runtime_behavior",
        "Biomimetic growth guidance covers phyllotaxis, branching, DLA-style, and venation-like patterns.",
        False,
        False,
    ),
    "Generative Geometry Library": (
        "implemented_runtime_behavior",
        "The bounded geometry catalog acts as the reusable deterministic pattern library.",
        False,
        False,
    ),
    "Algorithm Recommendation": (
        "implemented_runtime_behavior",
        "Detected intent ranks catalog entries and emits algorithm recommendations per pattern.",
        False,
        False,
    ),
    "Interactive Geometry Preview": (
        "product_hitl_required",
        "Preview/UI mutation is intentionally not implemented because V8.3 requested no broad preview changes.",
        True,
        True,
    ),
    "Geometry Demo Assets": (
        "product_hitl_required",
        "Actual asset generation needs product/HITL selection of target scenes and artifact format.",
        True,
        True,
    ),
}



__all__ = [
    "BLUEPRINT_ROWS",
    "DOMAIN_RUNTIME_NAMES",
    "GEOMETRY_ALIASES",
    "GeometryBlueprintRow",
    "ROADMAP_CLASSIFICATION_ROWS",
    "UNSUPPORTED_CLAIM_TOKENS",
]
