"""Static workflow runtime node constants."""
from __future__ import annotations

from creative_coding_assistant.orchestration.runtime.nodes.contracts import _WorkflowModelPayloadSpec

ASSISTANT_WORKFLOW_NODE_ORDER: tuple[str, ...] = (
    "intake",
    "routing",
    "memory",
    "retrieval",
    "context_assembly",
    "prompt_input",
    "planning",
    "director",
    "reasoning",
    "prompt_rendering",
    "generation",
    "artifact_extraction",
    "preview_preparation",
    "artifact_critique",
    "review",
    "refinement",
    "finalization",
    "failure",
)

ASSISTANT_WORKFLOW_RECURSION_LIMIT = 40

_FINAL_EVENT_MODEL_PAYLOAD_KEYS: tuple[str, ...] = (
    "clarification",
    "creative_intent",
    "creative_hierarchy",
    "creative_strategy",
    "creative_techniques",
    "creative_plan",
    "creative_constraints",
    "creative_constraint_priorities",
    "runtime_capabilities",
    "creative_tradeoffs",
    "creative_quality_prediction",
    "symbolic_narrative",
    "creative_composition",
    "procedural_structure",
    "generative_structure",
    "semantic_motif",
    "emotional_consistency",
    "cross_modality",
    "audio_visual_scene",
    "artifact_plan",
    "artifact_dependency_graph",
    "runtime_compatibility",
    "artifact_capability_matrix",
    "multi_artifact_strategy",
    "artifact_critic",
    "artifact_refiner",
    "artifact_intelligence_synthesis",
    "artifact_merge_planner",
    "artifact_export_intelligence",
    "artifact_engine_contracts",
    "evaluation_engine_contracts",
    "creative_critic",
    "self_evaluation",
    "creative_improvement_planner",
    "reflection_loop",
    "creative_confidence",
    "creative_score",
    "consistency_validation",
    "evaluation_report",
    "creative_director",
    "creative_reasoning",
)

_WORKFLOW_RUNTIME_MODEL_PAYLOAD_SPECS: tuple[_WorkflowModelPayloadSpec, ...] = (
    _WorkflowModelPayloadSpec("creative_plan", "creative_plan", "planning_available"),
    _WorkflowModelPayloadSpec(
        "creative_intent",
        "creative_intent",
        "intent_decomposer_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_hierarchy",
        "creative_hierarchy",
        "hierarchy_planner_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_strategy",
        "creative_strategy",
        "strategy_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_techniques",
        "creative_techniques",
        "technique_selector_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_constraints",
        "creative_constraints",
        "constraint_solver_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_constraint_priorities",
        "creative_constraint_priorities",
        "constraint_prioritizer_available",
    ),
    _WorkflowModelPayloadSpec(
        "runtime_capabilities",
        "runtime_capabilities",
        "runtime_capability_reasoner_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_tradeoffs",
        "creative_tradeoffs",
        "tradeoff_explorer_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_quality_prediction",
        "creative_quality_prediction",
        "quality_predictor_available",
    ),
    _WorkflowModelPayloadSpec(
        "symbolic_narrative",
        "symbolic_narrative",
        "symbolic_narrative_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_composition",
        "creative_composition",
        "creative_composition_available",
    ),
    _WorkflowModelPayloadSpec(
        "procedural_structure",
        "procedural_structure",
        "procedural_structure_available",
    ),
    _WorkflowModelPayloadSpec(
        "generative_structure",
        "generative_structure",
        "generative_structure_available",
    ),
    _WorkflowModelPayloadSpec(
        "semantic_motif",
        "semantic_motif",
        "semantic_motif_available",
    ),
    _WorkflowModelPayloadSpec(
        "emotional_consistency",
        "emotional_consistency",
        "emotional_consistency_available",
    ),
    _WorkflowModelPayloadSpec(
        "cross_modality",
        "cross_modality",
        "cross_modality_available",
    ),
    _WorkflowModelPayloadSpec(
        "audio_visual_scene",
        "audio_visual_scene",
        "audio_visual_scene_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_plan",
        "artifact_plan",
        "artifact_planner_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_dependency_graph",
        "artifact_dependency_graph",
        "artifact_dependency_graph_available",
    ),
    _WorkflowModelPayloadSpec(
        "runtime_compatibility",
        "runtime_compatibility",
        "runtime_compatibility_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_capability_matrix",
        "artifact_capability_matrix",
        "artifact_capability_matrix_available",
    ),
    _WorkflowModelPayloadSpec(
        "multi_artifact_strategy",
        "multi_artifact_strategy",
        "multi_artifact_strategy_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_critic",
        "artifact_critic",
        "artifact_critic_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_refiner",
        "artifact_refiner",
        "artifact_refiner_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_intelligence_synthesis",
        "artifact_intelligence_synthesis",
        "artifact_intelligence_synthesis_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_merge_planner",
        "artifact_merge_planner",
        "artifact_merge_planner_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_export_intelligence",
        "artifact_export_intelligence",
        "artifact_export_intelligence_available",
    ),
    _WorkflowModelPayloadSpec(
        "artifact_engine_contracts",
        "artifact_engine_contracts",
        "artifact_engine_contracts_available",
    ),
    _WorkflowModelPayloadSpec(
        "evaluation_engine_contracts",
        "evaluation_engine_contracts",
        "evaluation_engine_contracts_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_critic",
        "creative_critic",
        "creative_critic_available",
    ),
    _WorkflowModelPayloadSpec(
        "self_evaluation",
        "self_evaluation",
        "self_evaluation_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_improvement_planner",
        "creative_improvement_planner",
        "creative_improvement_planner_available",
    ),
    _WorkflowModelPayloadSpec(
        "reflection_loop",
        "reflection_loop",
        "reflection_loop_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_confidence",
        "creative_confidence",
        "creative_confidence_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_score",
        "creative_score",
        "creative_score_available",
    ),
    _WorkflowModelPayloadSpec(
        "consistency_validation",
        "consistency_validation",
        "consistency_validation_available",
    ),
    _WorkflowModelPayloadSpec(
        "evaluation_report",
        "evaluation_report",
        "evaluation_report_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_director",
        "creative_director",
        "director_available",
    ),
    _WorkflowModelPayloadSpec(
        "creative_reasoning",
        "creative_reasoning",
        "creative_reasoning_available",
    ),
)

def assistant_workflow_final_payload_keys() -> tuple[str, ...]:
    """Return final-event model payload keys in emission order."""

    return _FINAL_EVENT_MODEL_PAYLOAD_KEYS

def assistant_workflow_model_payload_specs() -> tuple[_WorkflowModelPayloadSpec, ...]:
    """Return workflow-state payload mappings in serialization order."""

    return _WORKFLOW_RUNTIME_MODEL_PAYLOAD_SPECS
